raise Exception('this is the error message')